export type RootStackParamList = {
  Login: undefined;
  Admin: undefined;
  CreateAdminAccount: undefined;
  LoginAdminAccount: undefined;
  Student: undefined;
  CreateStudentAccount: undefined;
  LoginStudentAccount: undefined;
  Teacher: undefined;
  CreateTeacherAccount: undefined;
  LoginTeacherAccount: undefined;
  CreateNewSchool: undefined;
  AdminHome: undefined;
  StudentHome: undefined;
  TeacherHome: undefined;
  TeacherYourClass: { className: string; section: string; classTeacher: string; studentsCount: number; subject: string };
  TeacherOtherClass: { className: string; section: string; classTeacher: string; studentsCount: number; subject: string };
  StudentAttendance: undefined;
  StudentAcademics: undefined;
  StudentCalendar: undefined;
  StudentConduct: undefined;
  StudentChatroom: undefined;
  StudentQuery: undefined;
  StudentSubmission: undefined;
};
